name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ^3.12.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: Nunito
    fonts:
      - asset: fonts/Nunito/Regular.ttf
      - asset: fonts/Nunito/Italic.ttf
        style: italic
  - family: SNPro
    fonts:
      - asset: fonts/SNPro/Regular.ttf
      - asset: fonts/SNPro/Italic.ttf
        style: italic


